### ISSUE TITLE
Bug in JMP_IND target construction for next_statement

### ISSUE THREAD

**Issue by tmcintos** [bradgrantham/apple2a#3]
Seems there is a typo here?

https://github.com/bradgrantham/apple2a/blob/98c79e5100f44562d7592a5bc7f8f57ff82cddcf/main.c#L1273C20-L1273C20

```
            // Jump to top of loop, indirectly through ptr1, which has the address.
            c[8] = I_JMP_IND;
            c[9] = (uint8_t) &ptr1 & 0x0F;     // <--- should be 0xFF?
            c[10] = (uint8_t) &ptr1 >> 8;
```

I was playing around with the code, and having all kinds of problems with FOR-NEXT loops until I changed this to 0xFF.

**Comment by lkesteloot** [comment]
That's crazy, you must be right, but I've written lots of programs with NEXT statements and they all worked fine. Could the second nybble always have been zero?

Thank you for the fix!

**Comment by lkesteloot** [comment]
The `ptr1` variable is actually placed in a static location by the compiler, so it's plausible that in my build that nybble was always zero, and in yours it's not.

**Comment by tmcintos** [comment]
Yeah, that’s probably why it didn’t show up before. I was playing around with porting this over to llvm-mos, and started with llvm’s pseudo-registers allocated at $00-$1F; I just added the cc65 `ptrN` registers as regular zero page variables to begin with, and these currently start at $20.

My hope was that using llvm-mos would result in reduced code size, but since I just did the naive thing and pulled in the necessary routines from cc65’s runtime, it ended up pretty much being a wash (*I didn’t realize this was coupled to the cc65 runtime when I first started*). Also, it seems llvm-mos still generates an unexpectedly large number of instructions at `-Oz` for things like taking the address of a zero page variable and passing it to a function as `unit8_t` (*seems like this should just be a single `LDA` immediate instruction*), which doesn’t help. And the difference in function calling conventions (*first arg in AX instead of last; others in zero page instead of on stack*) resulted in slightly larger code as well. I ended up having to abbreviate debug message strings and comment out unused cc65 runtime entry points to make it fit.

**Comment by lkesteloot** [comment]
That's too bad, I've always wanted to shrink the size so that I could add support for strings. Rewriting it all in assembly doesn't feel like a good use of time, but that might be the only way to do it.

**Comment by tmcintos** [comment]
Not sure, but I'm thinking there may be some opportunities for some further reduction by replacing the cc65 runtime routines with C equivalents; I believe there's some redundancy currently, for example as a result of duplicated multiplication and division routines (*since I'm pulling in cc65's and llvm-mos is bringing in its own*).

My original hope was to eventually have an open replacement for Apple II firmware (BASIC + Monitor with Apple-compatible entry points). I think that would require using the Monitor's I/O routines just to make things fit; I haven't looked at what it would take to move this over to using those. Originally, I had hoped to use the [AppleIIgo ROM](https://web.archive.org/web/20120328122628/http://www-personal.umich.edu/~mressl/appleiigo/pub/ROMs/), which is supposedly public domain, as a basis for the Monitor portion, but I gave up on that idea after noticing that most of it appears to be simply copied from the original firmware.  I'm not aware of any other alternative, so I assume the relevant monitor APIs would need to be entirely re-implemented, and at least that much would presumably need to be done in assembly, due to the entry point and size constraints.

**Comment by tmcintos** [comment]
FWIW:
- Under llvm-mos I currently have a bit over two free pages of ROM, vs less than one with cc65.
- I also did a quick port to SDCC, the utilization is slightly worse than llvm-mos.

**Comment by tmcintos** [comment]
Also, there's actually another error here:

            c[10] = (uint8_t) &ptr1 >> 8;

The cast has higher precedence than the shift, so the result is always zero (which is OK as long as `ptr1` is in the zero page).  Should be:

            c[10] = (uint8_t) (&ptr1 >> 8);

SDCC actually found that one.

**Comment by lkesteloot** [comment]
Your observation applies to the previous line as well. That's three bugs in two lines! But `ptr1` must be in the zero page, the code just above this requires it.

**Comment by lkesteloot** [comment]
> * Under llvm-mos I currently have a bit over two free pages of ROM, vs less than one with cc65.
> * I also did a quick port to SDCC, the utilization is slightly worse than llvm-mos.

Okay good to know, thank you!
